apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: roboshop
  labels:
    app: payments
    tier: app
    project: roboshop
    
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: payments
      tier: app
      project: roboshop
  template:
    metadata:
      labels:
        app: payments
        tier: app
        project: roboshop
    spec:
      containers:
      - name: payments
        image: {{ .Values.deployment.imageURL }}:{{ .Values.deployment.imageVersion }}
        envFrom:
        - configMapRef:
            name: payments
        


    
